### ISSUE TITLE
CQ is not defined error in CQ5.6.1

### ISSUE THREAD

**Issue by yupadhyay** [headwirecom/aem-solr-search#3]
Hey Gaston,

Great work on this. I tried to install this package on CQ5.6.1 But getting following error on author/publish when trying to view page.
![screen shot 2014-10-06 at 6 37 04 pm](https://cloud.githubusercontent.com/assets/3046343/4536263/2dd1371e-4dc3-11e4-95f9-9341c2fe6179.png)

I think it could be related to issue 1, But tried with latest code with same issue.

**Comment by paulrohrbeck** [comment]
Hi @yupadhyay,

any plan on adding that missing dependency?
